---
AllCops:
  Include:
    - "**/*.rb"
    - "Rakefile"
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes
